blank_issues_enabled: false
contact_links:
  - name: Dokumentation der Diplomarbeit
    url: https://cancani.com/diplomarbeit/
    about: Aktueller Stand der Arbeit, Kapitel 2 erklärt die Projektführung
